#!/usr/bin/env python3
"""Construit clean_mapping.csv : original_name,new_name,action (KEEP|RENAME|DELETE).

Règles : pas de Generic_*, EXCLUDE*, Plant_* dans new_name ; DELETE = images à écarter
(trash) ; ravageurs Pest_* ; acariens tomate/raisin/blé explicites → Crop_Spider_Mite.
"""
from __future__ import annotations

import csv
import re
from pathlib import Path

# Mapping intermédiaire (étape précédente) : original_folder -> label proposé
LEGACY: list[tuple[str, str]] = [
    ("Acrididae", "Pest_Grasshopper"),
    ("Africanized Honey Bees (Killer Bees)", "Pest_Honey_Bee"),
    ("Alfalfa_Leaf_Mosaic_Virus", "Alfalfa_Leaf_Mosaic_Virus"),
    ("Alluim_Leaf_Bacterial_Soft_Rot", "Allium_Leaf_Bacterial_Soft_Rot"),
    ("Alternaria black molds  stem cankers (Genus Alternaria Nees)", "Generic_Alternaria_Stem_Canker"),
    ("Alternaria_Leaf_Spot", "Generic_Alternaria_Leaf_Spot"),
    ("Angular_Leaf_Spot_Cucumber", "Cucumber_Angular_Leaf_Spot"),
    ("Anthracnose (Colletotrichum orbiculare (Berk. & Mo", "Cucurbit_Anthracnose"),
    ("Aphididae", "Pest_Aphid"),
    ("Aphids", "Pest_Aphid"),
    ("Aphids (1)", "Pest_Aphid"),
    ("Apple Brown_spot", "Apple_Brown_Spot"),
    ("Apple_Black_Rot", "Apple_Black_Rot"),
    ("Apple_Healthy", "Apple_Healthy"),
    ("Apple_Rotten", "Apple_Rotten"),
    ("Apple_Rust", "Apple_Cedar_Apple_Rust"),
    ("Apple_Scab", "Apple_Scab"),
    ("Apricot Normal", "Apricot_Healthy"),
    ("Apricot shot_hole", "Apricot_Shot_Hole_Disease"),
    ("Armyworm", "Pest_Armyworm"),
    ("Armyworms", "Pest_Armyworm"),
    ("Aspergillus ear and kernel rot (Aspergillus flavus Maize)", "Corn_Aspergillus_Ear_Rot"),
    ("Banana_Anthracnose", "Banana_Anthracnose"),
    ("Banana_Cordana", "Banana_Cordana_Leaf_Spot"),
    ("Banana_Cordana_Leaf_Spot", "Banana_Cordana_Leaf_Spot"),
    ("Banana_Healthy", "Banana_Healthy"),
    ("Banana_Leaf_Bunchy_Top_Virus", "Banana_Bunchy_Top_Virus"),
    ("Banana_Leaf_Streak_Virus", "Banana_Leaf_Streak_Virus"),
    ("Banana_Moko_Disease", "Banana_Moko_Disease"),
    ("Banana_Panama_Disease", "Banana_Fusarium_Wilt"),
    ("Banana_Pestalotiopsis_Leaf_Spot", "Banana_Pestalotiopsis_Leaf_Spot"),
    ("Banana_Rotten", "Banana_Rotten"),
    ("Banana_Sigatoka", "Banana_Sigatoka_Leaf_Spot"),
    ("Bean Fungal_leaf disease", "Bean_Fungal_Leaf_Disease"),
    ("Bean_Fungal_Disease", "Bean_Fungal_Leaf_Disease"),
    ("Bean_Halo_Blight", "Bean_Halo_Blight"),
    ("Bean_Healthy", "Bean_Healthy"),
    ("Bean_Leaf_Bacterial_Blight", "Bean_Leaf_Bacterial_Blight"),
    ("Bean_Leaf_Spot", "Bean_Leaf_Spot"),
    ("Bean_Mosaic", "Bean_Mosaic_Virus"),
    ("Bean_Rust", "Bean_Leaf_Rust"),
    ("Bean_Tobacco_Caterpillar", "Pest_Caterpillar"),
    ("Beet_Armyworm", "Pest_Beet_Armyworm"),
    ("Bell pepper_Fruit_Blossom_End_Rot", "Pepper_Bell_Fruit_Blossom_End_Rot"),
    ("Bellpepper_Healthy", "Pepper_Bell_Healthy"),
    ("Bellpepper_Rotten", "Pepper_Bell_Rotten"),
    ("Black Gram (Vigna mungo)_cercospora leaf spot", "Black_Gram_Cercospora_Leaf_Spot"),
    ("Black Gram (Vigna mungo)_healthy", "Black_Gram_Healthy"),
    ("Black Gram (Vigna mungo)_insect", "Pest_Insect"),
    ("Black Gram (Vigna mungo)_leaf Crinkle", "Black_Gram_Leaf_Crinkle_Virus"),
    ("Black Rot", "EXCLUDE_Unknown_Black_Rot"),
    ("Black_Cutworm", "Pest_Black_Cutworm"),
    ("Blackgram_Leaf_Crinkle_Virus", "Black_Gram_Leaf_Crinkle_Virus"),
    ("Blackgram_Yellow_Mosaic_Virus", "Black_Gram_Yellow_Mosaic_Virus"),
    ("Blister_Beetle", "Pest_Blister_Beetle"),
    ("Blueberry_Healthy", "Blueberry_Healthy"),
    ("Brassica_Black_leaf_spot", "Brassica_Black_Leaf_Spot"),
    ("Bread mold (Rhizopus stolonifer (Ehrenb.) Vuill.)", "Generic_Rhizopus_Bread_Mold"),
    ("Broad mite (Polyphagotarsonemus latus (Banks))", "Pest_Broad_Mite"),
    ("Brown Marmorated Stink Bugs", "Pest_Stink_Bug"),
    ("Brown_Rot_Fruit", "EXCLUDE_Unknown_Brown_Rot_Fruit"),
    ("Cabbage Loopers", "Pest_Cabbage_Looper"),
    ("Cabbage_Armyworm", "Pest_Cabbage_Armyworm"),
    ("Cabbage_Leaf_Bacterial_Blight", "Cabbage_Leaf_Bacterial_Blight"),
    ("Cabbage_Leaf_Bacterial_Soft_Rot", "Cabbage_Leaf_Bacterial_Soft_Rot"),
    ("Carota_ Alternaria_Fruit_Spot", "Carrot_Alternaria_Fruit_Spot"),
    ("Carrot_Root_Fly", "Pest_Carrot_Root_Fly"),
    ("Carrot__Healthy", "Carrot_Healthy"),
    ("Carrot__Rotten", "Carrot_Rotten"),
    ("Cashew_Anthracnose", "Cashew_Anthracnose"),
    ("Cashew_Gumosis", "Cashew_Gumosis"),
    ("Cashew_Healthy", "Cashew_Healthy"),
    ("Cashew_Leaf_Miner", "Pest_Leaf_Miner"),
    ("Cashew_Red_Rust", "Cashew_Red_Rust"),
    ("Cassava Bacterial Blight", "Cassava_Bacterial_Blight"),
    ("Cassava Brown Spot", "Cassava_Brown_Spot"),
    ("Cassava_Brown_Streak_Disease", "Cassava_Brown_Streak_Disease"),
    ("Cassava_Green_Mite", "Pest_Cassava_Green_Mite"),
    ("Cassava_Green_Mottle", "Cassava_Green_Mottle_Virus"),
    ("Cassava_Healthy", "Cassava_Healthy"),
    ("Cassava_Mosaic_Disease", "Cassava_Mosaic_Disease"),
    ("Cauliflower_Alternaria_leaf_spot", "Cauliflower_Alternaria_Leaf_Spot"),
    ("Cauliflower_Bacterial_Soft_Rot", "Cauliflower_Bacterial_Soft_Rot"),
    ("Cauliflower_Black_Rot", "Cauliflower_Black_Rot"),
    ("Cauliflower_Healthy", "Cauliflower_Healthy"),
    ("Cauliflower_Insect_Damage", "Pest_Insect"),
    ("Cerambycidae_Adult", "Pest_Longhorn_Beetle"),
    ("Cerambycidae_Larva", "Pest_Longhorn_Beetle_Larva"),
    ("Cereals_Leaf_Bacterial_Spot", "Cereal_Leaf_Bacterial_Spot"),
    ("Cherry Leaf Scorch", "Cherry_Leaf_Scorch"),
    ("Cherry_Healthy", "Cherry_Healthy"),
    ("Cherry_Leaf_Spot", "Cherry_Leaf_Spot"),
    ("Cherry_Powdery_Mildew", "Cherry_Powdery_Mildew"),
    ("Cherry_shot hole disease", "Cherry_Shot_Hole_Disease"),
    ("Chili_Cercospora_leaf_spot", "Chili_Cercospora_Leaf_Spot"),
    ("Chili_Condition", "EXCLUDE_Unlabeled"),
    ("Chili_Curl_Virus", "Chili_Leaf_Curl_Virus"),
    ("Chili_Nutrition_Deficiency", "Chili_Nutrient_Deficiency"),
    ("Chili_White_spot", "Chili_White_Spot"),
    ("Choanephora fruit rot (Choanephora cucurbitarum", "Cucurbit_Choanephora_Fruit_Rot"),
    ("Chrysomelidae_Adult", "Pest_Leaf_Beetle"),
    ("Chrysomelidae_Larva", "Pest_Leaf_Beetle_Larva"),
    ("Cicadellidae", "Pest_Leafhopper"),
    ("Citrillus_Fruit_Blossom_End_Rot", "Watermelon_Fruit_Blossom_End_Rot"),
    ("Citrullus_Bacterial_Fruit_Blotch", "Watermelon_Bacterial_Fruit_Blotch"),
    ("Citrullus_Bacterial_Leaf_Blotch", "Watermelon_Bacterial_Leaf_Blotch"),
    ("Citrus Canker", "Citrus_Canker"),
    ("Citrus_Black_Spot", "Citrus_Black_Spot"),
    ("Citrus_Black_spot", "Citrus_Black_Spot"),
    ("Citrus_Canker", "Citrus_Canker"),
    ("Citrus_Fruit_Disease", "Citrus_Fruit_Disease"),
    ("Citrus_Greening", "Citrus_Greening"),
    ("Citrus_Healthy", "Citrus_Healthy"),
    ("Citrus_Leaf_Greening", "Citrus_Greening"),
    ("Coccinellidae_Adult", "Pest_Lady_Beetle"),
    ("Coccinellidae_Larva", "Pest_Lady_Beetle_Larva"),
    ("Coffee__healthy", "Coffee_Healthy"),
    ("Coffee__rust", "Coffee_Leaf_Rust"),
    ("Colorado Potato Beetles", "Pest_Colorado_Potato_Beetle"),
    ("Corn Borers", "Pest_Corn_Borer"),
    ("Corn Earworms", "Pest_Corn_Earworm"),
    ("Corn Normal leaf", "Corn_Healthy"),
    ("Corn holcus_ leaf spot", "Corn_Holecus_Spot"),
    ("Corn smut (Ustilago maydis)", "Corn_Smut"),
    ("Corn_Cercospora_Leaf_Spot", "Corn_Gray_Leaf_Spot"),
    ("Corn_Common_Rust", "Corn_Common_Rust"),
    ("Corn_Grasshopper", "Pest_Grasshopper"),
    ("Corn_Gray_Leaf_Spot", "Corn_Gray_Leaf_Spot"),
    ("Corn_Healthy", "Corn_Healthy"),
    ("Corn_Leaf_Beetle", "Pest_Corn_Leaf_Beetle"),
    ("Corn_Leaf_Blight", "Corn_Leaf_Blight"),
    ("Corn_Leaf_Spot", "Corn_Leaf_Spot"),
    ("Corn_Northern_Leaf_Blight", "Corn_Northern_Leaf_Blight"),
    ("Corn_Rust", "Corn_Common_Rust"),
    ("Corn_Streak_Virus", "Corn_Streak_Virus"),
    ("Corn_cercospora_gray_leaf_spot", "Corn_Gray_Leaf_Spot"),
    ("Corn_cercospora_gray_leaf_spot (1)", "Corn_Gray_Leaf_Spot"),
    ("Corynespora leaf spot (Corynespora cassiicola", "Generic_Corynespora_Leaf_Spot"),
    ("Cotton  bollworm (Helicoverpa armigera)", "Pest_Cotton_Bollworm"),
    ("Cotton_Adult_Bollworm", "Pest_Cotton_Bollworm"),
    ("Cotton_Bacterial_Blight", "Cotton_Bacterial_Blight"),
    ("Cotton_Fusarium_wilt", "Cotton_Fusarium_Wilt"),
    ("Cotton_Healthy", "Cotton_Healthy"),
    ("Cotton_Larve_Bollworm", "Pest_Cotton_Bollworm"),
    ("Cotton_Virus", "Cotton_Leaf_Curl_Virus"),
    ("Cotton_fussarium_wilt", "Cotton_Fusarium_Wilt"),
    ("Cotton_fussarium_wilt (1)", "Cotton_Fusarium_Wilt"),
    ("Crambidae_Adult", "Pest_Crambid_Moth"),
    ("Crambidae_Larva", "Pest_Crambid_Larva"),
    ("Crucifers_Xanthomonas_campestris_pv_campestris_Black_rot)", "Crucifer_Black_Rot"),
    ("Cucumber__Rotten", "Cucumber_Rotten"),
    ("Cucumber__healthy", "Cucumber_Healthy"),
    ("Cucurbit_Leaf_Downy_Mildew", "Cucurbit_Downy_Mildew"),
    ("Curculionoidea (Weevil)", "Pest_Weevil"),
    ("Curcuma longa_Dry Leaf", "Turmeric_Dry_Leaf"),
    ("Curcuma longa_Healthy Leaf", "Turmeric_Healthy_Leaf"),
    ("Curcuma longa_Leaf Blotch", "Turmeric_Leaf_Blotch"),
    ("Curcuma longa_Rhizome Disease Root", "Turmeric_Rhizome_Rot"),
    ("Curcuma longa_Rhizome Healthy Root", "Turmeric_Healthy_Rhizome"),
    ("Damages_Fruit_Bollworm", "Pest_Bollworm"),
    ("Delphacidae", "Pest_Planthopper"),
    ("Elateridae_Adult", "Pest_Click_Beetle"),
    ("Elateridae_Larva", "Pest_Wireworm"),
    ("Fall Armyworms", "Pest_Fall_Armyworm"),
    ("Fall_Armyworm", "Pest_Fall_Armyworm"),
    ("Fig Blight_leaf disease", "Fig_Leaf_Blight"),
    ("Fig Brown spot", "Fig_Brown_Spot"),
    ("Fig normal leaf", "Fig_Healthy_Leaf"),
    ("Fig_rust leaf", "Fig_Leaf_Rust"),
    ("Flatidae", "Pest_Planthopper"),
    ("Flax_Budworm", "Pest_Flax_Budworm"),
    ("Flea_Beetle", "Pest_Flea_Beetle"),
    ("Flower blights (Genus Choanephora Curr.)", "Generic_Choanephora_Flower_Blight"),
    ("Fruit Flies", "Pest_Fruit_Fly"),
    ("Fulgoridae", "Pest_Planthopper"),
    ("Fusarium_Cereal_Head_Blight", "Cereal_Fusarium_Head_Blight"),
    ("Generic_Aphids", "Pest_Aphid"),
    ("Generic_Thrips", "Pest_Thrips"),
    ("Geotrichum_Rot_Cucurbitaceae_Fruit", "Cucurbit_Geotrichum_Sour_Rot"),
    ("Grape Anthracnose leaf", "Grape_Anthracnose"),
    ("Grape Brown spot leaf", "Grape_Brown_Spot"),
    ("Grape Downy mildew leaf", "Grape_Downy_Mildew"),
    ("Grape Mites_leaf disease", "Pest_Spider_Mite"),
    ("Grape Normal_leaf", "Grape_Healthy_Leaf"),
    ("Grape Powdery_mildew leaf", "Grape_Powdery_Mildew"),
    ("Grape shot hole leaf disease", "Grape_Shot_Hole_Disease"),
    ("Grape_Black_Measles", "Grape_Black_Measles"),
    ("Grape_Black_Rot", "Grape_Black_Rot"),
    ("Grape_Esca", "Grape_Esca"),
    ("Grape_Healthy", "Grape_Healthy"),
    ("Grape_Isariopsis_Leaf_Spot", "Grape_Isariopsis_Leaf_Spot"),
    ("Grape_Isariopsis_Leaf_Spot (1)", "Grape_Isariopsis_Leaf_Spot"),
    ("Grape_Leaf_Esca", "Grape_Esca"),
    ("Grape_Leaf_Leafroll_Virus", "Grape_Leafroll_Virus"),
    ("Grape_Leaf_Spot", "Grape_Leaf_Spot"),
    ("Gryllotalpidaeç", "Pest_Mole_Cricket"),
    ("Guava_Healthy_Fruit", "Guava_Healthy_Fruit"),
    ("Guava_Healthy_Leaf", "Guava_Healthy_Leaf"),
    ("Hibiscus_Citrus_Pot", "EXCLUDE"),
    ("Hibiscus_Early_Mild_Spotting", "Hibiscus_Leaf_Spot"),
    ("Hibiscus_Fungal_Infection", "Hibiscus_Fungal_Leaf_Spot"),
    ("Hibiscus_Healthy", "Hibiscus_Healthy"),
    ("Hibiscus_Mild_Edge_Damage", "EXCLUDE"),
    ("Hibiscus_Senescent", "EXCLUDE"),
    ("Hibiscus_Slightly_Diseased", "EXCLUDE"),
    ("Hibiscus_Wrinkled_Leaf", "Hibiscus_Leaf_Wrinkling"),
    ("Hosta_Leaf_Virus_X", "Hosta_Virus_X"),
    ("Jackfruit Leaf_Blight", "Jackfruit_Leaf_Blight"),
    ("Jackfruit Leaf_Dried", "Jackfruit_Dried_Leaf"),
    ("Jackfruit Leaf_Fungal_Spot", "Jackfruit_Fungal_Leaf_Spot"),
    ("Jackfruit Leaf_Healthy", "Jackfruit_Healthy_Leaf"),
    ("Jackfruit Leaf_Leaf_Miner", "Pest_Leaf_Miner"),
    ("Jackfruit Leaf_Pest_Damage", "Pest_Insect"),
    ("Jackfruit Leaf_Senescence", "EXCLUDE"),
    ("Jackfruit Leaf_Young", "EXCLUDE"),
    ("Jamun__diseased", "Jamun_Disease"),
    ("Late_Blight_Fruit", "EXCLUDE_Unknown_Late_Blight_Fruit"),
    ("Late_Blight_Leaf", "EXCLUDE_Unknown_Late_Blight_Leaf"),
    ("Leaf_Bacterial_Wilt", "EXCLUDE_Unknown_Bacterial_Wilt"),
    ("Leaf_Curl_Virus", "EXCLUDE_Unknown_Leaf_Curl_Virus"),
    ("Leaf_Spurge_Flea_Beetle", "Pest_Flea_Beetle"),
    ("Legume_Blister_Beetle", "Pest_Blister_Beetle"),
    ("Lemon__healthy", "Lemon_Healthy"),
    ("Lettuce Chlorosis Virus (LCV) (Crinivirus Lettuce Chlorosis Virus)", "Lettuce_Chlorosis_Virus"),
    ("Limacodidae_Adult", "Pest_Slug_Caterpillar"),
    ("Limacodidae_Larva", "Pest_Slug_Caterpillar_Larva"),
    ("Lokat Normal leaf", "Wood_Apple_Healthy_Leaf"),
    ("Longhorn_Beetle", "Pest_Longhorn_Beetle"),
    ("Loose smut of wheat or barley (Ustilago tritici (Pers.) Rostr.)", "Wheat_Loose_Smut"),
    ("Lychee_Anthrax_Leaf", "Lychee_Anthracnose"),
    ("Lychee_Bituminous_Leaf", "Lychee_Bituminous_Leaf_Spot"),
    ("Lychee_Curl_Leaf", "Lychee_Leaf_Curl"),
    ("Lychee_Deficiency_Leaf", "Lychee_Nutrient_Deficiency"),
    ("Lychee_Dry_Leaf", "Lychee_Dry_Leaf"),
    ("Lychee_Felt_Leaf", "Lychee_Eriophyid_Mite"),
    ("Lychee_Healthy", "Lychee_Healthy"),
    ("Lychee_Leaf_Blight", "Lychee_Leaf_Blight"),
    ("Lychee_Leaf_Gall", "Lychee_Leaf_Gall"),
    ("Maize Grasshopper", "Pest_Grasshopper"),
    ("Maize leaf beetle", "Pest_Maize_Leaf_Beetle"),
    ("Maize_Tar_Spot", "Corn_Tar_Spot"),
    ("Maize_leaf blight", "Corn_Leaf_Blight"),
    ("Maize_leaf spot", "Corn_Leaf_Spot"),
    ("Maize_streak virus", "Corn_Streak_Virus"),
    ("Mango_Diseased_Fruit", "Mango_Diseased_Fruit"),
    ("Mango_Healthy", "Mango_Healthy"),
    ("Mango_Healthy_Fruit", "Mango_Healthy_Fruit"),
    ("Mango_Healthy_Leaf", "Mango_Healthy_Leaf"),
    ("Mango_Rotten", "Mango_Rotten"),
    ("Mealybug", "Pest_Mealybug"),
    ("Miridae", "Pest_Plant_Bug"),
    ("Niphad Grape_Downey Mildew", "Grape_Downy_Mildew"),
    ("Niphad Grape_Healthy Leaves", "Grape_Healthy"),
    ("Niphad Grape_Powdery Mildew", "Grape_Powdery_Mildew"),
    ("Noctuidae_Adult", "Pest_Owl_Moth"),
    ("Noctuidae_Larva", "Pest_Cutworm_Larva"),
    ("Northern_Maize_Leaf_Blight", "Corn_Northern_Leaf_Blight"),
    ("Nymphalidae_Adult", "Pest_Butterfly"),
    ("Nymphalidae_Larva", "Pest_Caterpillar"),
    ("Orange_Citrus_Greening", "Citrus_Greening"),
    ("Orange__Haunglongbing_(Citrus_greening)", "Citrus_Greening"),
    ("Orange__Rotten", "Orange_Rotten"),
    ("Paddy_Bacterial_Blight", "Rice_Bacterial_Blight"),
    ("Papaya_Diseased_Fruit", "Papaya_Diseased_Fruit"),
    ("Papaya_Healthy_Fruit", "Papaya_Healthy_Fruit"),
    ("Papaya_Healthy_Leaf", "Papaya_Healthy_Leaf"),
    ("Papaya_Ring_Spot", "Papaya_Ringspot_Virus"),
    ("Papilionidae_Adult", "Pest_Swallowtail"),
    ("Papilionidae_Larva", "Pest_Swallowtail_Larva"),
    ("Peach_Bacterial_spot", "Peach_Bacterial_Spot"),
    ("Peach_Bacterial_spot (1)", "Peach_Bacterial_Spot"),
    ("Peach_Healthy", "Peach_Healthy"),
    ("Peach_Healthy (1)", "Peach_Healthy"),
    ("Peanut_Early_leaf_spot", "Peanut_Early_Leaf_Spot"),
    ("Peanut_Late_leaf_spot", "Peanut_Late_Leaf_Spot"),
    ("Pear Black spot _ leaf disease", "Pear_Black_Spot"),
    ("Pear Normal _leaf", "Pear_Healthy_Leaf"),
    ("Penicillium fungi (Genus Penicillium Link)", "Generic_Penicillium_Blue_Mold"),
    ("Pepper_Bacterial_Spot", "Pepper_Bacterial_Spot"),
    ("Pepper_Bell_Bacterial_Spot", "Pepper_Bell_Bacterial_Spot"),
    ("Pepper_Bell_Healthy", "Pepper_Bell_Healthy"),
    ("Pepper_Healthy", "Pepper_Healthy"),
    ("Pest_Ant", "Pest_Ant"),
    ("Pest_Aphids", "Pest_Aphid"),
    ("Pest_Bee", "Pest_Honey_Bee"),
    ("Pest_Beetle", "Pest_Beetle"),
    ("Pest_Boxelder_bug", "Pest_Boxelder_Bug"),
    ("Pest_Cabbage_looper", "Pest_Cabbage_Looper"),
    ("Pest_Caterpillar", "Pest_Caterpillar"),
    ("Pest_Corn_borer", "Pest_Corn_Borer"),
    ("Pest_Earthworm", "Pest_Earthworm"),
    ("Pest_Earwig", "Pest_Earwig"),
    ("Pest_Fall_Armyworm", "Pest_Fall_Armyworm"),
    ("Pest_Flea_Beetle", "Pest_Flea_Beetle"),
    ("Pest_Grasshopper", "Pest_Grasshopper"),
    ("Pest_Icerya_purchasi", "Pest_Cottony_Cushion_Scale"),
    ("Pest_Mole_cricket", "Pest_Mole_Cricket"),
    ("Pest_Moth", "Pest_Moth"),
    ("Pest_Peach_borer", "Pest_Peach_Borer"),
    ("Pest_Rice_borer", "Pest_Rice_Stem_Borer"),
    ("Pest_Rice_leaf_roller", "Pest_Rice_Leaf_Roller"),
    ("Pest_Rice_planthopper", "Pest_Rice_Planthopper"),
    ("Pest_Rice_water_weevil", "Pest_Rice_Water_Weevil"),
    ("Pest_Scirtothrips_dorsalis", "Pest_Thrips"),
    ("Pest_Slug", "Pest_Slug"),
    ("Pest_Snail", "Pest_Snail"),
    ("Pest_Thrips", "Pest_Thrips"),
    ("Pest_Unaspis_yanonensis", "Pest_Arrowhead_Scale"),
    ("Pest_Wasp", "Pest_Wasp"),
    ("Pest_Weevil", "Pest_Weevil"),
    ("Pest_Wheat_aphid", "Pest_Aphid"),
    ("Pest_Wheat_mite", "Pest_Spider_Mite"),
    ("Pest_Wheat_stem_fly", "Pest_Wheat_Stem_Fly"),
    ("Pest_Whitefly", "Pest_Whitefly"),
    ("Phytophthora_Blight_Cucurbitaceae", "Cucurbit_Phytophthora_Blight"),
    ("Pomegranate__Healthy", "Pomegranate_Healthy"),
    ("Potato_Early_Blight", "Potato_Early_Blight"),
    ("Potato_Healthy", "Potato_Healthy"),
    ("Potato_Late_Blight", "Potato_Late_Blight"),
    ("Potato__Rotten", "Potato_Rotten"),
    ("Potyvirus_Mosaic_Virus", "Generic_Potyvirus_Mosaic"),
    ("Pumpkin_Bacterial Leaf Spot", "Pumpkin_Bacterial_Leaf_Spot"),
    ("Pumpkin_Downy Mildew", "Pumpkin_Downy_Mildew"),
    ("Pumpkin_Healthy Leaf", "Pumpkin_Healthy"),
    ("Pumpkin_Mosaic Disease", "Pumpkin_Mosaic_Virus"),
    ("Pumpkin_Powdery_Mildew", "Pumpkin_Powdery_Mildew"),
    ("Pythium diseases (Genus Pythium Pringsh.)", "Generic_Pythium_Damping_Off"),
    ("Radish_Black_Rot", "Radish_Black_Rot"),
    ("Radish_Mosaic_Virus", "Radish_Mosaic_Virus"),
    ("Raspberry__healthy", "Raspberry_Healthy"),
    ("RedRot", "EXCLUDE_Unknown_Red_Rot"),
    ("Red_Spider_Mite", "Pest_Spider_Mite"),
    ("Rhizopus soft rots (Genus Rhizopus Ehrenb.)", "Generic_Rhizopus_Soft_Rot"),
    ("Rice_Brown_Spot", "Rice_Brown_Spot"),
    ("Rice_Healthy", "Rice_Healthy"),
    ("Rice_Hispa", "Pest_Rice_Hispa"),
    ("Rice_Leaf_Blast", "Rice_Leaf_Blast"),
    ("Rice_Leaf_scald", "Rice_Leaf_Scald"),
    ("Rice___Neck_Blast", "Rice_Neck_Blast"),
    ("Root_Knot_Nematode", "Pest_Root_Knot_Nematode"),
    ("Rose Leaf Holes", "Rose_Leaf_Holes"),
    ("Rose Leaf_Black Spot", "Rose_Black_Spot"),
    ("Rose_Healthy Leaf", "Rose_Healthy"),
    ("Scarabaeidae_Adult", "Pest_Scarab_Beetle"),
    ("Scarabaeidae_Larva", "Pest_White_Grub"),
    ("Sclerotinia sclerotiorum_Fruit_Rot", "Generic_Sclerotinia_Fruit_Rot"),
    ("Sclerotinia sclerotiorum_Leaf_Rot", "Generic_Sclerotinia_Leaf_Rot"),
    ("Sclerotinia sclerotiorum_Stem_Rot", "Generic_Sclerotinia_Stem_Rot"),
    ("Sclerotinia timber rot (Sclerotinia sclerotiorum)", "Generic_Sclerotinia_Timber_Rot"),
    ("Solanaceae_Bacterial_Soft_Rot", "Solanaceae_Bacterial_Soft_Rot"),
    ("Solanaceae_Bacterial_Spot", "Solanaceae_Bacterial_Spot"),
    ("Southern red mite (Oligonychus ilicis)", "Pest_Spider_Mite"),
    ("Southern root-knot nematode", "Pest_Root_Knot_Nematode"),
    ("Soybean_Leaf_Halo_Blight", "Soybean_Halo_Blight"),
    ("Soybean_Leaf_Mosaic_Virus", "Soybean_Mosaic_Virus"),
    ("Soybean_Leaf_Rust", "Soybean_Leaf_Rust"),
    ("Soybean_Tospovirus_Leaf_Vein_Necrosis_Virus", "Soybean_Tospovirus_Leaf_Vein_Necrosis"),
    ("Soybean__diabrotica_speciosa", "Pest_Soybean_Beetle"),
    ("Soybean__healthy", "Soybean_Healthy"),
    ("Soybean__mosaic_virus", "Soybean_Mosaic_Virus"),
    ("Soybean__powdery_mildew", "Soybean_Powdery_Mildew"),
    ("Sphingidae_Adult", "Pest_Hawk_Moth"),
    ("Sphingidae_Larva", "Pest_Hornworm"),
    ("Sphinx_Moth_Adult", "Pest_Hawk_Moth"),
    ("Sphinx_Moth_Larve_Damages", "Pest_Hornworm"),
    ("Spider Mites", "Pest_Spider_Mite"),
    ("Spider_Mite_Leaf_Damages", "Pest_Spider_Mite"),
    ("Spotted_Wilt_Virus", "Generic_Spotted_Wilt_Virus"),
    ("Squash__Powdery_mildew", "Squash_Powdery_Mildew"),
    ("Stem_Borer_Leaf_Damages", "Pest_Stem_Borer"),
    ("Strawberry_Healthy", "Strawberry_Healthy"),
    ("Strawberry_Healthy (1)", "Strawberry_Healthy"),
    ("Strawberry_Leaf_Scorch", "Strawberry_Leaf_Scorch"),
    ("Strawberry__Rotten", "Strawberry_Rotten"),
    ("Sugar_Yellow", "Sugarcane_Yellow_Leaf"),
    ("Sugarcane_Healthy", "Sugarcane_Healthy"),
    ("Sugarcane_Healthy (1)", "Sugarcane_Healthy"),
    ("Sugarcane_Mosaic_virus", "Sugarcane_Mosaic_Virus"),
    ("Sugarcane_RedRot", "Sugarcane_Red_Rot"),
    ("Sugarcane_RedRot (1)", "Sugarcane_Red_Rot"),
    ("Sugarcane_Red_Rot", "Sugarcane_Red_Rot"),
    ("Sugarcane_Rust", "Sugarcane_Rust"),
    ("Sugarcane_Rust (2)", "Sugarcane_Rust"),
    ("Sugarcane_Yellow", "Sugarcane_Yellow_Leaf"),
    ("Sugarcane_Yellow (1)", "Sugarcane_Yellow_Leaf"),
    ("Sugarcane_Yellow_Leaf", "Sugarcane_Yellow_Leaf"),
    ("Sweet_Potato_Fruit_Feathery_Mottle_Virus", "Sweet_Potato_Feathery_Mottle_Virus"),
    ("Sweet_Potato_Leaf_Feathery_Mottle_Virus", "Sweet_Potato_Feathery_Mottle_Virus"),
    ("Target_Spot_Leaf", "Generic_Target_Spot"),
    ("Tarnished_Plant_Bug", "Pest_Tarnished_Plant_Bug"),
    ("Tea_Algal_Spot", "Tea_Algal_Leaf_Spot"),
    ("Tea_Brown_Blight", "Tea_Brown_Blight"),
    ("Tea_Grey_Blight", "Tea_Grey_Blight"),
    ("Tea_Healthy", "Tea_Healthy"),
    ("Tea_Red_Spot", "Tea_Red_Spot"),
    ("Tea_Red_leaf_spot", "Tea_Red_Leaf_Spot"),
    ("Thrips", "Pest_Thrips"),
    ("Thrips_Leaf_Damages", "Pest_Thrips"),
    ("Tobacco_Leaf_Etch_Virus", "Tobacco_Etch_Virus"),
    ("Tobacco_Leaf_Ringspot_Virus", "Tobacco_Ringspot_Virus"),
    ("Tomato Hornworms", "Pest_Hornworm"),
    ("Tomato Two Spotted Spider Mite", "Pest_Spider_Mite"),
    ("Tomato_Bacterial_Spot", "Tomato_Bacterial_Spot"),
    ("Tomato_Early_Blight", "Tomato_Early_Blight"),
    ("Tomato_Fruit_Bacterial_Canker", "Tomato_Fruit_Bacterial_Canker"),
    ("Tomato_Fruit_Blossom_End_Rot", "Tomato_Fruit_Blossom_End_Rot"),
    ("Tomato_Healthy", "Tomato_Healthy"),
    ("Tomato_Late_Blight", "Tomato_Late_Blight"),
    ("Tomato_Leaf_Bacterial_Canker", "Tomato_Leaf_Bacterial_Canker"),
    ("Tomato_Leaf_Blight", "Tomato_Leaf_Blight"),
    ("Tomato_Leaf_Curl", "Tomato_Leaf_Curl_Virus"),
    ("Tomato_Leaf_Mold", "Tomato_Leaf_Mold"),
    ("Tomato_Leaf_Mosaic_Virus", "Tomato_Mosaic_Virus"),
    ("Tomato_Leaf_Septoria", "Tomato_Septoria_Leaf_Spot"),
    ("Tomato_Mosaic_Virus", "Tomato_Mosaic_Virus"),
    ("Tomato_Septoria_Leaf_Spot", "Tomato_Septoria_Leaf_Spot"),
    ("Tomato_Spider_Mite", "Pest_Spider_Mite"),
    ("Tomato_Spider_mites_Two_spotted_spider_mite", "Pest_Spider_Mite"),
    ("Tomato_Target_Spot", "Tomato_Target_Spot"),
    ("Tomato_Verticillium_Wilt", "Tomato_Verticillium_Wilt"),
    ("Tomato_Yellow_Leaf_Curl_Virus", "Tomato_Yellow_Leaf_Curl_Virus"),
    ("Tomato__Rotten", "Tomato_Rotten"),
    ("Twospotted spider mite (Tetranychus urticae Koch)", "Pest_Spider_Mite"),
    ("Walnut Anthracnose_leaf disease", "Walnut_Anthracnose"),
    ("Walnut Blotch_leaf disease", "Walnut_Leaf_Blotch"),
    ("Walnut Normal_leaf", "Walnut_Healthy_Leaf"),
    ("Walnut Shot_hole", "Walnut_Shot_Hole_Disease"),
    ("Western Corn Rootworms", "Pest_Western_Corn_Rootworm"),
    ("Wheat_Aphid", "Pest_Aphid"),
    ("Wheat_Aphid (1)", "Pest_Aphid"),
    ("Wheat_Black_Rust", "Wheat_Stem_Rust"),
    ("Wheat_Black_Rust (1)", "Wheat_Stem_Rust"),
    ("Wheat_Blast", "Wheat_Blast"),
    ("Wheat_Blast (1)", "Wheat_Blast"),
    ("Wheat_Brown_Rust", "Wheat_Leaf_Rust"),
    ("Wheat_Brown_Rust (1)", "Wheat_Leaf_Rust"),
    ("Wheat_Common_Root_Rot", "Wheat_Common_Root_Rot"),
    ("Wheat_Common_Root_Rot (1)", "Wheat_Common_Root_Rot"),
    ("Wheat_Fusarium_head_blight", "Wheat_Fusarium_Head_Blight"),
    ("Wheat_Healthy", "Wheat_Healthy"),
    ("Wheat_Healthy (1)", "Wheat_Healthy"),
    ("Wheat_Leaf_Streak_Mosaic_Virus", "Wheat_Leaf_Streak_Mosaic_Virus"),
    ("Wheat_Leaf_blight", "Wheat_Leaf_Blight"),
    ("Wheat_Mildew", "Wheat_Powdery_Mildew"),
    ("Wheat_Mildew (1)", "Wheat_Powdery_Mildew"),
    ("Wheat_Mite", "Pest_Spider_Mite"),
    ("Wheat_Septoria", "Wheat_Septoria_Blotch"),
    ("Wheat_Smut", "Wheat_Smut"),
    ("Wheat_Smut (1)", "Wheat_Smut"),
    ("Wheat_Stem_fly", "Pest_Wheat_Stem_Fly"),
    ("Wheat_Tan_spot", "Wheat_Tan_Spot"),
    ("Wheat_Yellow_rust", "Wheat_Yellow_Rust"),
    ("Whiteflies_Leaf", "Pest_Whitefly"),
    ("Wireworm", "Pest_Wireworm"),
    ("alfalfa_plant_bug", "Pest_Alfalfa_Plant_Bug"),
    ("beetle", "Pest_Beetle"),
    ("blast blé", "Wheat_Blast"),
    ("bollworm", "Pest_Bollworm"),
    ("chili_healthy", "Chili_Healthy"),
    ("fall armyworm (Spodoptera frugiperda) Dammage", "Pest_Fall_Armyworm"),
    ("fall armyworm (Spodoptera frugiperda) Larve", "Pest_Fall_Armyworm_Larva"),
    ("fall armyworm (Spodoptera frugiperda) Larve adults", "Pest_Fall_Armyworm"),
    ("gauva_diseased", "Guava_Disease"),
    ("healthy blé", "Wheat_Healthy"),
    ("insect blé", "Pest_Insect"),
    ("kudzu bug (Megacopta cribraria (Fabricius))", "Pest_Kudzu_Bug"),
    ("leaf_folder blé", "Pest_Leaf_Folder"),
    ("lesser cornstalk borer (Elasmopalpus lignosella)", "Pest_Lesser_Cornstalk_Borer"),
    ("lokat Leaf_spot", "Wood_Apple_Leaf_Spot"),
    ("maize fall army worm", "Pest_Fall_Armyworm"),
    ("persimmons Brown_spot", "Persimmon_Brown_Spot"),
    ("rhododendron stem borer (Oberea myops", "Pest_Rhododendron_Stem_Borer"),
    ("root rotdamping off (Genus Rhizoctonia DC.)", "Generic_Rhizoctonia_Damping_Off"),
    ("root-knot nematode (Genus Meloidogyne)", "Pest_Root_Knot_Nematode"),
    ("scald blé", "Wheat_Leaf_Scald"),
    ("stem-boring weevil (Mecinus janthinus Germar)", "Pest_Stem_Boring_Weevil"),
    ("stripes blé", "Wheat_Yellow_Rust"),
    ("tomato spider mites", "Pest_Spider_Mite"),
    ("tomato_healthy_leaf", "Tomato_Healthy"),
    ("tomato_leaf_miner", "Pest_Tomato_Leaf_Miner"),
    ("tomato_septoria_leaf", "Tomato_Septoria_Leaf_Spot"),
    ("tungro blé", "Rice_Tungro_Disease"),
]


def _collapse_underscores(s: str) -> str:
    return re.sub(r"_+", "_", s.strip("_"))


def polish_label(s: str) -> str:
    """Underscores propres, pas de suffixe (1)/(2) sur le label."""
    if not s:
        return s
    x = s.strip()
    x = x.replace(" ", "_")
    x = _collapse_underscores(x)
    x = re.sub(r"_\(\d+\)$", "", x)
    return x


def canonical_original_key(original: str) -> str:
    """Clé de comparaison loose original → label (pour KEEP)."""
    x = original.strip()
    x = re.sub(r"\s+", "_", x)
    x = x.replace("-", "_")
    x = _collapse_underscores(x)
    x = re.sub(r"_\(\d+\)$", "", x)
    return x


def is_forbidden_intermediate(label: str) -> bool:
    if not label:
        return True
    if label == "EXCLUDE" or label.startswith("EXCLUDE_"):
        return True
    if label.startswith("Generic_"):
        return True
    if label.startswith("Plant_"):
        return True
    return False


def spider_mite_label(original: str, prev: str) -> str:
    if prev != "Pest_Spider_Mite":
        return prev
    o = original.lower()
    if "tomato" in o:
        return "Tomato_Spider_Mite"
    if "grape" in o or "niphad" in o:
        return "Grape_Spider_Mite"
    if "wheat" in o or "wheat_mite" in o.replace(" ", "_") or "blé" in o or "blé" in o:
        return "Wheat_Spider_Mite"
    return "Pest_Spider_Mite"


def refine_label(original: str, prev_new: str) -> str:
    s = spider_mite_label(original, prev_new)
    if s == "Crucifer_Black_Rot":
        return "Cabbage_Black_Rot"
    if s == "Cereal_Fusarium_Head_Blight":
        return "Wheat_Fusarium_Head_Blight"
    return s


def to_final_row(original: str, prev_new: str) -> tuple[str, str, str]:
    if is_forbidden_intermediate(prev_new):
        return original, "", "DELETE"
    if prev_new.startswith("Solanaceae_"):
        return original, "", "DELETE"
    if prev_new == "Cereal_Leaf_Bacterial_Spot":
        return original, "", "DELETE"
    if prev_new == "Pest_Insect":
        return original, "", "DELETE"

    name = polish_label(refine_label(original, prev_new))

    if canonical_original_key(original) == name:
        return original, name, "KEEP"
    return original, name, "RENAME"


def main() -> None:
    root = Path(__file__).resolve().parent
    out = root / "clean_mapping.csv"
    if len(LEGACY) != 482:
        raise SystemExit(f"Attendu 482 entrées LEGACY, obtenu {len(LEGACY)}")

    rows = [to_final_row(o, n) for o, n in LEGACY]

    with out.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["original_name", "new_name", "action"])
        w.writerows(rows)

    n_del = sum(1 for _, _, a in rows if a == "DELETE")
    n_keep = sum(1 for _, _, a in rows if a == "KEEP")
    n_re = sum(1 for _, _, a in rows if a == "RENAME")
    print(f"Écrit {out} : DELETE={n_del} KEEP={n_keep} RENAME={n_re}")


if __name__ == "__main__":
    main()
