FROM python:3.11-slim

WORKDIR /backend

COPY ./backend /backend

RUN pip install --upgrade pip && \
    pip install -r /app/requirements.txt  # en supposant que tu gardes tout dans requirements.txt

EXPOSE 8000

CMD ["uvicorn", "fastapi_server:app", "--host", "0.0.0.0", "--port", "8000"]
